const STORE_TYPE = 'app';

export const CHECK_IS_LOGIN = `${STORE_TYPE}/CHECK_IS_LOGIN`;
export const LOG_IN = `${STORE_TYPE}/LOG_IN`;
export const LOG_IN_SUCCESS = `${STORE_TYPE}/LOG_IN_SUCCESS`;
export const LOG_IN_FAILURE = `${STORE_TYPE}/LOG_IN_FAILURE`;

export const TOGGLE_NEW_USER = `${STORE_TYPE}/TOGGLE_NEW_USER`;

export const SIGN_UP = `${STORE_TYPE}/SIGN_UP`;
export const SIGN_UP_SUCCESS = `${STORE_TYPE}/SIGN_UP_SUCCESS`;
export const SIGN_UP_FAILURE = `${STORE_TYPE}/SIGN_UP_FAILURE`;

export const BANK_CARD = `${STORE_TYPE}/BANK_CARD`;
export const BANK_CARD_SUCCESS = `${STORE_TYPE}/BANK_CARD_SUCCESS`;
export const BANK_CARD_FAILURE = `${STORE_TYPE}/BANK_CARD_FAILURE`;
